# Generated by Django 5.2.17 on 2026-09-23 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='batches/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inspection.batch')),
            ],
            options={
                'ordering': ['batch', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('images', models.ManyToManyField(blank=True, related_name='evaluation_sets', to='inspection.productimage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('needs_review', 'Needs more review')], max_length=20)),
                ('rationale', models.TextField()),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('baseline_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline_decisions', to='inspection.modelversion')),
                ('candidate_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_decisions', to='inspection.modelversion')),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_decisions', to=settings.AUTH_USER_MODEL)),
                ('evaluation_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='inspection.evaluationset')),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground_truth_label', models.CharField(blank=True, choices=[('ok', 'OK / No Defect'), ('scratch', 'Scratch'), ('dent', 'Dent'), ('discoloration', 'Discoloration'), ('crack', 'Crack')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_obj', to='inspection.productimage')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('field_changed', models.CharField(max_length=50)),
                ('old_value', models.CharField(blank=True, max_length=200)),
                ('new_value', models.CharField(blank=True, max_length=200)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='inspection.review')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_class', models.CharField(choices=[('ok', 'OK / No Defect'), ('scratch', 'Scratch'), ('dent', 'Dent'), ('discoloration', 'Discoloration'), ('crack', 'Crack')], max_length=30)),
                ('confidence', models.FloatField(help_text='0.0 - 1.0')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processed', 'Processed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='inspection.modelversion')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='inspection.productimage')),
            ],
            options={
                'ordering': ['-processed_at'],
                'unique_together': {('image', 'model_version')},
            },
        ),
    ]
